export const STUDENTS_DATA = [
  {
    id: 1,
    name: 'Ahsan Khan',
    fathersName: 'Mohammad Khan',
    mothersName: 'Fatima Khan',
    address: '123 Maple St, Dhaka',
    class: '5',
    phone: '01636428991',
    gender: 'male',
  },
  {
    id: 2,
    name: 'Fatima Rahman',
    fathersName: 'Abdul Rahman',
    mothersName: 'Sultana Rahman',
    address: '456 Oak St, Chittagong',
    class: '6',
    phone: '01636428992',
    gender: 'female',
  },
  {
    id: 3,
    name: 'Rafiq Ahmed',
    fathersName: 'Jamal Ahmed',
    mothersName: 'Nasima Ahmed',
    address: '789 Pine St, Khulna',
    class: '5',
    phone: '01636428993',
    gender: 'male',
  },
  {
    id: 4,
    name: 'Nusrat Jahan',
    fathersName: 'Salim Jahan',
    mothersName: 'Razia Jahan',
    address: '321 Elm St, Sylhet',
    class: '7',
    phone: '01636428994',
    gender: 'female',
  },
  {
    id: 5,
    name: 'Shakib Al Hasan',
    fathersName: 'Mohammad Al Hasan',
    mothersName: 'Ayesha Al Hasan',
    address: '654 Cedar St, Rajshahi',
    class: '6',
    phone: '01636428995',
    gender: 'male',
  },
  {
    id: 6,
    name: 'Maya Begum',
    fathersName: 'Khaled Begum',
    mothersName: 'Sadia Begum',
    address: '987 Birch St, Barisal',
    class: '8',
    phone: '01636428996',
    gender: 'female',
  },
  {
    id: 7,
    name: 'Rohit Das',
    fathersName: 'Suresh Das',
    mothersName: 'Anita Das',
    address: '159 Spruce St, Comilla',
    class: '5',
    phone: '01636428997',
    gender: 'male',
  },
  {
    id: 8,
    name: 'Sofia Islam',
    fathersName: 'Tariq Islam',
    mothersName: 'Nabila Islam',
    address: '753 Willow St, Narayanganj',
    class: '7',
    phone: '01636428998',
    gender: 'female',
  },
  {
    id: 9,
    name: 'Arif Hossain',
    fathersName: 'Khaled Hossain',
    mothersName: 'Shabnam Hossain',
    address: '852 Fir St, Bogura',
    class: '6',
    phone: '01636428999',
    gender: 'male',
  },
  {
    id: 10,
    name: 'Nabila Sultana',
    fathersName: 'Rafique Sultana',
    mothersName: 'Laila Sultana',
    address: '369 Maple Ave, Pabna',
    class: '8',
    phone: '01636428000',
    gender: 'female',
  },
];

export const CLASS_OPTIONS = [
  { value: '6', lavel: 'Six' },
  { value: '7', lavel: 'Seven' },
  { value: '8', lavel: 'Eight' },
  { value: '9', lavel: 'Nine' },
  { value: '10', lavel: 'Ten' },
];

export const GENDER_OPTIONS = [
  { value: 'male', lavel: 'Male' },
  { value: 'female', lavel: 'Female' },
];
