export const STUDENTS_DATA = [
  {
    id: 1,
    name: 'Ahsan Khan',
    fathersName: 'Mohammad Khan',
    mothersName: 'Fatima Khan',
    address: '123 Maple St, Dhaka',
    class: '6',
    phone: '01636428991',
    gender: 'male',
    roll: 1,
  },
  {
    id: 2,
    name: 'Fatima Rahman',
    fathersName: 'Abdul Rahman',
    mothersName: 'Sultana Rahman',
    address: '456 Oak St, Chittagong',
    class: '6',
    phone: '01636428992',
    gender: 'female',
    roll: 2,
  },
  {
    id: 3,
    name: 'Rafiq Ahmed',
    fathersName: 'Jamal Ahmed',
    mothersName: 'Nasima Ahmed',
    address: '789 Pine St, Khulna',
    class: '6',
    phone: '01636428993',
    gender: 'male',
    roll: 3,
  },
  {
    id: 4,
    name: 'Shakib Al Hasan',
    fathersName: 'Mohammad Al Hasan',
    mothersName: 'Ayesha Al Hasan',
    address: '654 Cedar St, Rajshahi',
    class: '6',
    phone: '01636428995',
    gender: 'male',
    roll: 4,
  },
  {
    id: 5,
    name: 'Arif Hossain',
    fathersName: 'Khaled Hossain',
    mothersName: 'Shabnam Hossain',
    address: '852 Fir St, Bogura',
    class: '6',
    phone: '01636428999',
    gender: 'male',
    roll: 5,
  },
  {
    id: 6,
    name: 'Nusrat Jahan',
    fathersName: 'Salim Jahan',
    mothersName: 'Razia Jahan',
    address: '321 Elm St, Sylhet',
    class: '7',
    phone: '01636428994',
    gender: 'female',
    roll: 1,
  },
  {
    id: 7,
    name: 'Sofia Islam',
    fathersName: 'Tariq Islam',
    mothersName: 'Nabila Islam',
    address: '753 Willow St, Narayanganj',
    class: '7',
    phone: '01636428998',
    gender: 'female',
    roll: 2,
  },
  {
    id: 8,
    name: 'Maya Begum',
    fathersName: 'Khaled Begum',
    mothersName: 'Sadia Begum',
    address: '987 Birch St, Barisal',
    class: '7',
    phone: '01636428996',
    gender: 'female',
    roll: 3,
  },
  {
    id: 9,
    name: 'Rohit Das',
    fathersName: 'Suresh Das',
    mothersName: 'Anita Das',
    address: '159 Spruce St, Comilla',
    class: '7',
    phone: '01636428997',
    gender: 'male',
    roll: 4,
  },
  {
    id: 10,
    name: 'Nabila Sultana',
    fathersName: 'Rafique Sultana',
    mothersName: 'Laila Sultana',
    address: '369 Maple Ave, Pabna',
    class: '7',
    phone: '01636428000',
    gender: 'female',
    roll: 5,
  },
  {
    id: 11,
    name: 'John Doe',
    fathersName: 'Mr. Doe',
    mothersName: 'Mrs. Doe',
    address: '123 Main St, Dhaka',
    class: '8',
    phone: '01636428001',
    gender: 'male',
    roll: 1,
  },
  {
    id: 12,
    name: 'Jane Smith',
    fathersName: 'Mr. Smith',
    mothersName: 'Mrs. Smith',
    address: '456 Side St, Chittagong',
    class: '8',
    phone: '01636428002',
    gender: 'female',
    roll: 2,
  },
  {
    id: 13,
    name: 'Michael Johnson',
    fathersName: 'Mr. Johnson',
    mothersName: 'Mrs. Johnson',
    address: '789 Back St, Khulna',
    class: '8',
    phone: '01636428003',
    gender: 'male',
    roll: 3,
  },
  {
    id: 14,
    name: 'Emily Williams',
    fathersName: 'Mr. Williams',
    mothersName: 'Mrs. Williams',
    address: '321 Front St, Sylhet',
    class: '8',
    phone: '01636428004',
    gender: 'female',
    roll: 4,
  },
  {
    id: 15,
    name: 'David Brown',
    fathersName: 'Mr. Brown',
    mothersName: 'Mrs. Brown',
    address: '654 Hill St, Rajshahi',
    class: '8',
    phone: '01636428005',
    gender: 'male',
    roll: 5,
  },
  {
    id: 16,
    name: 'Matthew Thompson',
    fathersName: 'Mr. Thompson',
    mothersName: 'Mrs. Thompson',
    address: '852 Valley St, Bogura',
    class: '9',
    phone: '01636428006',
    gender: 'male',
    roll: 1,
  },
  {
    id: 17,
    name: 'Ashley Garcia',
    fathersName: 'Mr. Garcia',
    mothersName: 'Mrs. Garcia',
    address: '159 River St, Comilla',
    class: '9',
    phone: '01636428007',
    gender: 'female',
    roll: 2,
  },
  {
    id: 18,
    name: 'Andrew Martinez',
    fathersName: 'Mr. Martinez',
    mothersName: 'Mrs. Martinez',
    address: '753 Lake St, Narayanganj',
    class: '9',
    phone: '01636428008',
    gender: 'male',
    roll: 3,
  },
  {
    id: 19,
    name: 'Jessica Harris',
    fathersName: 'Mr. Harris',
    mothersName: 'Mrs. Harris',
    address: '369 Ocean St, Dhaka',
    class: '9',
    phone: '01636428009',
    gender: 'female',
    roll: 4,
  },
  {
    id: 20,
    name: 'Christopher Martin',
    fathersName: 'Mr. Martin',
    mothersName: 'Mrs. Martin',
    address: '456 Sea St, Chittagong',
    class: '9',
    phone: '01636428010',
    gender: 'male',
    roll: 5,
  },
  {
    id: 21,
    name: 'Lisa Thomas',
    fathersName: 'Mr. Thomas',
    mothersName: 'Mrs. Thomas',
    address: '789 Hill St, Khulna',
    class: '10',
    phone: '01636428011',
    gender: 'female',
    roll: 1,
  },
  {
    id: 22,
    name: 'James Jackson',
    fathersName: 'Mr. Jackson',
    mothersName: 'Mrs. Jackson',
    address: '321 Mountain St, Sylhet',
    class: '10',
    phone: '01636428012',
    gender: 'male',
    roll: 2,
  },
  {
    id: 23,
    name: 'Daniel White',
    fathersName: 'Mr. White',
    mothersName: 'Mrs. White',
    address: '654 Forest St, Rajshahi',
    class: '10',
    phone: '01636428013',
    gender: 'male',
    roll: 3,
  },
  {
    id: 24,
    name: 'Sophia Brown',
    fathersName: 'Mr. Brown',
    mothersName: 'Mrs. Brown',
    address: '852 Park St, Bogura',
    class: '10',
    phone: '01636428014',
    gender: 'female',
    roll: 4,
  },
  {
    id: 25,
    name: 'Oliver Twist',
    fathersName: 'Mr. Twist',
    mothersName: 'Mrs. Twist',
    address: '159 Garden St, Comilla',
    class: '10',
    phone: '01636428015',
    gender: 'male',
    roll: 5,
  },
];

export const CLASS_OPTIONS = [
  { value: '6', lavel: 'Six' },
  { value: '7', lavel: 'Seven' },
  { value: '8', lavel: 'Eight' },
  { value: '9', lavel: 'Nine' },
  { value: '10', lavel: 'Ten' },
];

export const GENDER_OPTIONS = [
  { value: 'male', lavel: 'Male' },
  { value: 'female', lavel: 'Female' },
];
