export const TEACHERS_DATA = [
  {
    id: 1,
    name: 'Mohammad Rahman',
    subject: 'Mathematics',
    phone: '01636428995',
    email: 'mohammad.rahman@school.com',
    gender: 'male',
  },
  {
    id: 2,
    name: 'Fatima Begum',
    subject: 'English',
    phone: '01786428996',
    email: 'fatima.begum@school.com',
    gender: 'female',
  },
  {
    id: 3,
    name: 'Abdul Karim',
    subject: 'Science',
    phone: '01976428997',
    email: 'abdul.karim@school.com',
    gender: 'male',
  },
  {
    id: 4,
    name: 'Ayesha Sultana',
    subject: 'History',
    phone: '01676428998',
    email: 'ayesha.sultana@school.com',
    gender: 'female',
  },
  {
    id: 5,
    name: 'Rashedul Islam',
    subject: 'Physical Education',
    phone: '01866428999',
    email: 'rashedul.islam@school.com',
    gender: 'male',
  },
];
